# Конфигурация разрешенных VK пользователей
# Список VK user ID, которые могут авторизоваться в приложении

allowed_vk_users:
  # Пример:
  # - "123456789"  # VK user ID администратора
  # - "987654321"  # VK user ID другого пользователя
  
  # Добавьте VK user ID разрешенных пользователей:
  # - "your_vk_user_id_here"

# Инструкции:
# 1. Узнайте VK user ID через https://vk.com/settings или API
# 2. Добавьте ID в список выше
# 3. Перезапустите приложение для применения изменений

# Альтернатива: используйте переменную окружения ALLOWED_VK_USERS
# Пример: ALLOWED_VK_USERS="123456789,987654321" 