apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}-frontend
{{- end }}
---
{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-qdrant
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}-qdrant
spec:
  type: {{ .Values.qdrant.service.type }}
  ports:
  - port: {{ .Values.qdrant.service.port }}
    targetPort: 6333
    protocol: TCP
    name: http
  - port: {{ .Values.qdrant.service.grpcPort }}
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: {{ .Values.app.name }}-qdrant
{{- end }} 